In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
sns.set_context('talk')

import numpy as np
from numpy import array
import pandas as pd

In [3]:
# Import and process data

data = pd.read_csv('data.csv')
for i in range(len(data)):
    data.at[i, 'final_test_rews_0'] = eval(data.at[i, 'final_test_rews_0'])
    data.at[i, 'final_test_rews_0.25'] = eval(data.at[i, 'final_test_rews_0.25'])
    data.at[i, 'final_test_rews_0.5'] = eval(data.at[i, 'final_test_rews_0.5'])
    data.at[i, 'final_test_rews_1'] = eval(data.at[i, 'final_test_rews_1'])
    data.at[i, 'final_train_rews'] = eval(data.at[i, 'final_train_rews'])
    data.at[i, 'train_rews'] = eval(data.at[i, 'train_rews'])

In [4]:
# preview data
data.head()

Unnamed: 0  seed save_file  force_overwrite  weight_std_reward  \
0           0     0  data.csv            False               0.00   
1           0     0  data.csv            False               0.50   
2           0     0  data.csv            False               0.00   
3           0     0  data.csv            False               0.25   
4           0     0  data.csv            False               0.00   

   weight_std_policy     env_name  std_obs_scale_train std_obs_scales_test  \
0               0.00  CartPole-v1                  0.0   [0, 0.25, 0.5, 1]   
1               0.00  CartPole-v1                  0.0   [0, 0.25, 0.5, 1]   
2               0.50  CartPole-v1                  0.0   [0, 0.25, 0.5, 1]   
3               0.25  CartPole-v1                  0.0   [0, 0.25, 0.5, 1]   
4               0.00  CartPole-v1                  0.0   [0, 0.25, 0.5, 1]   

  search_method  ...  n_iterations    T  n_evals  top_k  \
0            RS  ...            30  200       10      5   
1            RS  ...            30  200       10      5   
2            RS  ...            30  200       10      5   
3            RS  ...            30  200       10      5   
4           CEM  ...            30  200       10      5   

                                          train_rews  \
0  [9.5, 147.1, 152.7, 157.8, 188.1, 188.8, 150.9...   
1  [9.92912878474779, 144.2071209296968, 164.7561...   
2  [36.77210630803543, 207.8014216509091, 198.057...   
3  [22.800014468682754, 215.11603143189376, 211.8...   
4  [9.3, 178.9, 200.0, 200.0, 200.0, 200.0, 200.0...   

                                    final_train_rews  \
0  [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200...   
1  [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200...   
2  [200.0, 200.0, 200.0, 182.0, 200.0, 200.0, 200...   
3  [200.0, 200.0, 164.0, 200.0, 180.0, 200.0, 200...   
4  [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200...   

                                   final_test_rews_0  \
0  [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200...   
1  [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200...   
2  [200.0, 200.0, 176.0, 200.0, 200.0, 177.0, 168...   
3  [198.0, 200.0, 200.0, 200.0, 200.0, 200.0, 167...   
4  [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200...   

                                final_test_rews_0.25  \
0  [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200...   
1  [200.0, 200.0, 200.0, 200.0, 158.0, 200.0, 200...   
2  [158.0, 200.0, 200.0, 200.0, 200.0, 148.0, 200...   
3  [162.0, 189.0, 200.0, 188.0, 168.0, 200.0, 200...   
4  [189.0, 200.0, 200.0, 122.0, 200.0, 200.0, 200...   

                                 final_test_rews_0.5  \
0  [102.0, 154.0, 200.0, 200.0, 195.0, 200.0, 111...   
1  [200.0, 155.0, 135.0, 117.0, 200.0, 200.0, 200...   
2  [190.0, 144.0, 200.0, 167.0, 132.0, 200.0, 177...   
3  [183.0, 137.0, 26.0, 200.0, 127.0, 151.0, 200....   
4  [130.0, 85.0, 67.0, 88.0, 140.0, 150.0, 97.0, ...   

                                   final_test_rews_1  
0  [117.0, 27.0, 125.0, 145.0, 136.0, 167.0, 132....  
1  [95.0, 33.0, 145.0, 39.0, 34.0, 46.0, 139.0, 4...  
2  [36.0, 30.0, 130.0, 99.0, 163.0, 22.0, 31.0, 9...  
3  [95.0, 159.0, 14.0, 64.0, 21.0, 143.0, 116.0, ...  
4  [16.0, 70.0, 24.0, 94.0, 33.0, 120.0, 21.0, 50...  

[5 rows x 23 columns]

In [5]:
# Example: Get rows that uses the RS search method:
np.r_[data.loc[data['std_obs_scale_train'] == 0]['final_train_rews'].to_list()]

array([[200., 200., 200., ..., 200., 200., 200.],
       [200., 200., 200., ..., 200., 200., 200.],
       [200., 200., 200., ..., 200., 200., 200.],
       ...,
       [200., 200., 200., ..., 200., 200., 200.],
       [200., 200., 200., ..., 200., 200., 200.],
       [200., 200., 200., ..., 200., 200., 200.]])

In [6]:
# Example: Get train rewards of rows that uses the RS search method as an np array:
np.r_[data.loc[data['search_method'] == 'RS']['final_test_rews_0'].to_list()]

array([[200., 200., 200., ..., 200., 200., 200.],
       [200., 200., 200., ..., 200., 200., 200.],
       [200., 200., 176., ..., 200., 200., 200.],
       ...,
       [ 97.,  83., 155., ...,  74., 200., 200.],
       [151., 184.,  84., ..., 112., 115.,  85.],
       [160.,  78.,  67., ...,  66., 200., 200.]])

In [7]:
# Example: Get train rewards of rows that uses the RS search method and trained w/ std_obs_scale_train=0.5 as an np array:
np.c_[data.loc[ (data['seed'] == 0) & (data['search_method'] == 'RS') & (data['std_obs_scale_train'] == 0) & (data['weight_std_reward'] == 0) & (data['weight_std_policy'] == 0)]['final_test_rews_0'].to_list()][0]

array([200., 200., 200., 200., 200., 200., 200., 200., 200., 200.])

In [75]:
# Example: Get train rewards of rows that uses the RS search method and trained w/ std_obs_scale_train=0.5 as an np array:
np.r_[data.loc[(data['search_method'] == 'GA') & (data['seed'] == 0) & (data['std_obs_scale_train'] == 1)]['final_test_rews_1'].to_list()]

array([[110.,  92.,  89.,  78.,  70.,  30.,  60.,  36.,  58.,  52.],
       [199.,  81.,  30., 141., 200., 120., 158., 114.,  48., 150.],
       [ 81., 143., 168., 172., 111., 135., 123., 139., 122., 137.],
       [200., 101., 118.,  58., 200.,  81., 200., 200., 116., 109.],
       [141., 200., 131., 153., 116., 188.,  91., 156., 110., 159.],
       [ 54.,  67.,  47.,  64.,  69.,  69., 146., 104., 122., 137.],
       [200., 200., 200., 200., 200.,  75., 200., 140., 200., 200.],
       [101.,  56., 102.,  76.,  73., 122., 120., 100.,  93., 156.]])

In [56]:
np.r_[data.loc[data['seed'] == 1]['final_test_rews_0.25'].to_list()]

array([[200., 171., 200., ..., 200., 200., 200.],
       [137., 200., 200., ..., 148., 200., 128.],
       [142., 156., 137., ..., 200., 171., 128.],
       ...,
       [158., 151., 162., ..., 173., 163., 146.],
       [122., 170., 180., ..., 144., 116., 114.],
       [200., 119., 155., ..., 160., 129., 122.]])

In [62]:
np.c_[data.loc[(data['search_method'] == 'RS') & (data['seed'] == '0')]['final_test_rews_0'].to_list()]

IndexError: index 1 is out of bounds for axis 0 with size 0

In [102]:
np.r_[data.loc[ (data['seed'] == 0) & (data['search_method'] == 'GA')]['final_test_rews_1'].to_list()][0]

array([81., 36., 57., 79., 79., 15., 77., 82., 16., 19.])