In [1]:
import numpy as np

In [482]:
#a=np.array([[24., 31., 32., 27., 53., 21., 26., 15., 27., 29.]])
#b=np.array([[26., 24., 22., 23., 45., 27., 44., 21., 23., 38.]])
a=np.array([[110.,  92.,  89.,  78.,  70.,  30.,  60.,  36.,  58.,  52.],
       [199.,  81.,  30., 141., 200., 120., 158., 114.,  48., 150.],
       [ 81., 143., 168., 172., 111., 135., 123., 139., 122., 137.],
       [200., 101., 118.,  58., 200.,  81., 200., 200., 116., 109.],
       [141., 200., 131., 153., 116., 188.,  91., 156., 110., 159.],
       [ 54.,  67.,  47.,  64.,  69.,  69., 146., 104., 122., 137.],
       [200., 200., 200., 200., 200.,  75., 200., 140., 200., 200.],
       [101.,  56., 102.,  76.,  73., 122., 120., 100.,  93., 156.]])

In [483]:
b=np.sum(a, axis=1)

In [484]:
print(b)

[ 675. 1241. 1331. 1383. 1445.  879. 1815.  999.]


In [485]:
c=np.sum(b)

In [486]:
print(c)

9768.0


In [487]:
a.shape

(8, 10)

In [488]:
c/80

122.1

In [489]:
np.std(a)

50.77243346541507

In [445]:
#e=np.mean([a, b, c], axis=0) 

In [1118]:
#f=np.std([a, b, c], axis=0) 

In [1119]:
#j=np.sum(e, axis=1)

In [1120]:
#e.shape

(1, 10)

In [1121]:
#j/10

array([30.03333333])

In [1122]:
#k=np.sum(f, axis=1)

In [1123]:
#f.shape

(1, 10)

In [1124]:
#k/10

array([7.37317219])